name: バグ報告
description: アプリケーションのバグや不具合を報告
title: "[Bug] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        バグ報告にご協力いただきありがとうございます。
        以下の情報を可能な限り詳しく記入してください。

  - type: textarea
    id: description
    attributes:
      label: バグの説明
      description: バグの内容を具体的に説明してください
      placeholder: 何が起こっているか、何が期待されているかを説明してください
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 再現手順
      description: バグを再現するための手順を記載してください
      placeholder: |
        1. '...'に移動
        2. '...'をクリック
        3. '...'まで下にスクロール
        4. エラーが表示される
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 期待される動作
      description: 本来どのように動作すべきかを説明してください
      placeholder: 正常な場合の動作を記載してください
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: 実際の動作
      description: 実際にどのような動作になっているかを説明してください
      placeholder: 現在の問題のある動作を記載してください
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: スクリーンショット
      description: 該当する場合は、スクリーンショットを添付してください
      placeholder: スクリーンショットをここにドラッグ＆ドロップ

  - type: dropdown
    id: severity
    attributes:
      label: 重要度
      description: このバグの重要度を選択してください
      options:
        - 🔴 Critical - アプリが使用できない
        - 🟠 High - 主要機能に影響がある
        - 🟡 Medium - 一部機能に影響がある
        - 🟢 Low - 軽微な問題
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: ブラウザ
      description: 使用しているブラウザを選択してください
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - その他

  - type: input
    id: browser-version
    attributes:
      label: ブラウザバージョン
      description: ブラウザのバージョンを記載してください
      placeholder: 例：Chrome 120.0.6099.130

  - type: dropdown
    id: device
    attributes:
      label: デバイス
      description: 使用しているデバイスを選択してください
      options:
        - デスクトップ (Windows)
        - デスクトップ (Mac)
        - デスクトップ (Linux)
        - モバイル (iOS)
        - モバイル (Android)
        - タブレット

  - type: textarea
    id: additional
    attributes:
      label: 追加情報
      description: その他、参考になる情報があれば記載してください
      placeholder: エラーメッセージ、コンソールログ、関連する情報など
