name: Code Quality Validation

# コード変更の品質を検証: ファイルサイズ、デバッグコード、セキュリティチェック
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-files:
    name: Check Modified Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for large files
        run: |
          git diff --name-only origin/${{ github.base_ref }}...HEAD | while read file; do
            if [ -f "$file" ]; then
              size=$(wc -c < "$file")
              if [ $size -gt 1048576 ]; then
                echo "❌ Large file detected: $file ($(numfmt --to=iec-i --suffix=B $size))"
                echo "Files larger than 1MB should not be committed"
                exit 1
              fi
            fi
          done
          echo "✅ No large files detected"

      - name: Check for debug code
        run: |
          if git diff origin/${{ github.base_ref }}...HEAD | grep -E "console\.(log|debug|info|warn)" | grep "^+"; then
            echo "⚠️  Warning: console statements found in changes"
            echo "Consider removing debug console statements before merging"
          else
            echo "✅ No console statements in changes"
          fi

      - name: Check for TODOs
        run: |
          if git diff origin/${{ github.base_ref }}...HEAD | grep "^+" | grep -i "TODO"; then
            echo "⚠️  Warning: TODO comments found in changes"
            echo "Consider addressing TODOs or creating issues for them"
          else
            echo "✅ No TODO comments in changes"
          fi

  security-check:
    name: Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for secrets
        run: |
          if git diff origin/${{ github.base_ref }}...HEAD | grep -E "(api[_-]?key|secret|password|token)" | grep "^+" | grep -v "NEXT_PUBLIC"; then
            echo "❌ Potential secret detected in changes"
            echo "Review changes for accidentally committed secrets"
            exit 1
          fi
          echo "✅ No obvious secrets detected"

      - name: Check for sensitive files
        run: |
          if git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -E "\.env$|\.env\.local$|credentials"; then
            echo "❌ Sensitive file detected in changes"
            echo "Do not commit .env files or credentials"
            exit 1
          fi
          echo "✅ No sensitive files in changes"
